### ISSUE TITLE
Align types for enum usage

### ISSUE THREAD

**Issue by microshine** [googleapis/nodejs-security-private-ca#141]
For most cases, Protos use mixed types for enums `<enum> | keyof typeof <enum>`

```
/** CertificateAuthority state. */
public state: (google.cloud.security.privateca.v1.CertificateAuthority.State|keyof typeof google.cloud.security.privateca.v1.CertificateAuthority.State);

/** KeyVersionSpec algorithm */
algorithm?: (google.cloud.security.privateca.v1.CertificateAuthority.SignHashAlgorithm|keyof typeof google.cloud.security.privateca.v1.CertificateAuthority.SignHashAlgorithm|null);
```

But `knownExtensions` filed with enum `KnownCertificateExtension` doesn't do the same

```
/** CertificateExtensionConstraints knownExtensions */
knownExtensions?: (google.cloud.security.privateca.v1.CertificateExtensionConstraints.KnownCertificateExtension[]|null);
```

**Comment by sofisl** [comment]
Hi @microshine, 

This library is autogenerated from the protos that come directly from API publishers themselves, not the client libraries. Would you mind elaborating what your use case is for this request? Perhaps we can submit a bug internally, or find some other solution.
