### ISSUE TITLE
More Sample examples for this module

### ISSUE THREAD

**Issue by mahendrabagul** [googleapis/nodejs-security-private-ca#45]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
I recently used this project for accessing Google CAS. The examples given are limited. While working I developed the understanding and I created small simple code snippets. 
 **Describe the solution you'd like**
A small code snippet for every other method available from this library.
 **Describe alternatives you've considered**
NA
 **Additional context**
I have got sample code, can I add them here?

**Comment by sofisl** [comment]
Thanks for adding, @mahendrabagul! Our samples have a series of requirements in internal docs that might be hard to consolidate, plus we generally ask the API owners to maintain any additional samples. However, if you want to add your samples to this issue tracker, I'll make the API owners aware that these are requested!
